### ISSUE TITLE
Can’t edit setup nodes

### ISSUE THREAD

**Issue by Fernando-Checa** [hufftheweevil/node-red-contrib-things#38]
From last NR update, I can’t add or edit things from setup nodes.
When I try to add or modify a thing, save button does not work. It just ignores it.
And if I press Done, changes are lost.

If I press cancel it works, but not save.

Also trying to create a new setup node fails.
I add a new thing and the screen looks like this.

![IMG_1841](https://user-images.githubusercontent.com/1741686/195627585-d7167eb5-2043-4003-96f8-6428b0ad7ecb.jpeg)

Tried from different devices and browser with same result.

Any idea what could be causing this behavior?

Thanks in advance

**Comment by hufftheweevil** [comment]
To help me diagnose the issue, what version of Node-RED were you using before updating? And what version are you using now?

**Comment by hufftheweevil** [comment]
Disregard - I figured it out.
Fixed in [v3.2.2](https://github.com/hufftheweevil/node-red-contrib-things/releases/tag/v3.2.2)

**Comment by Fernando-Checa** [comment]
It seems it's still happenings.
I'm using nodered 3.0.2 and also tried with  the new version of things 3.3.3.

I can create new set up nodes, but when I try to add new things, save does not work.

I'm exporting the node, edit the json and re import. Not very good but it works for now.

Let me know if I can do any kind of test for you.

Here is a video of the problem:

[https://streamable.com/xnxghl](url)

Thanks in advance

**Comment by hufftheweevil** [comment]
Ah, yes, seems to be a different issue. Thanks for the video! I'll do some more tests of my own when I get home tonight. Meanwhile, if you beat me to it, can open the browser's console (inspector) to see if it is throwing any errors there.

**Comment by hufftheweevil** [comment]
Very strange, I'm not able to reproduce the issue even when I follow your exact footsteps from creating a new Setup node at 1:33 in the video.

Let me know if you're getting any browser console errors when interacting with the Setup node UI, particularly when you press the Save button and nothing happens - that seems to be the catalyst. Also, what browser are you using?

Lastly, can create a new Setup node like you did in that video and export the node and paste here. Maybe that will give a clue.

**Comment by Fernando-Checa** [comment]
This happens on my PC (windows) using firefox and also happens on my iPad, using safari on a different nodered instalation in another place. 

I created a new node and this is the error when I hit save:
![imagen](https://user-images.githubusercontent.com/1741686/196362233-f2143e23-d09d-4bcd-a5ef-823b9880b4da.png)

and then the exported node:
`[
    {
        "id": "9b5e94486acde98a",
        "type": "Thing Setup",
        "z": "8158e2d7516003b1",
        "thingType": "newthing",
        "things": [],
        "state": [],
        "commands": [],
        "statusFunction": "",
        "debug": false,
        "x": 470,
        "y": 1320,
        "wires": []
    }
]`

**Comment by Fernando-Checa** [comment]
Whats also weird is that if I edit the setup node, the lower part was not visible until selecting a thing. Now it shows empty

![imagen](https://user-images.githubusercontent.com/1741686/196423013-c880995c-58cf-4b14-b41b-ddde3275df4a.png)

**Comment by hufftheweevil** [comment]
The thing editor should not be visible on the bottom like that. That was part of the issue that I fixed earlier.
If it is visible, then that means that when the Setup node is opened, the code that runs (`oneditprepare()`) is not finishing.
The reason that you're getting the error above is because you're using that lower part of the form when it's not supposed to be visible to you yet.
So the question now is... when you open the Setup node, is there any error message _before_ you try to add a new thing?

**Comment by Fernando-Checa** [comment]
ok, so when I double click on the setup node, before doing anything, I get:

![imagen](https://user-images.githubusercontent.com/1741686/196631377-b03467ed-2be7-4c6d-8e8e-66fafb6f00ee.png)

if then I try to modify a thing and add a prop, then hit save:

![imagen](https://user-images.githubusercontent.com/1741686/196631821-0df359a4-4ffe-45f4-8e57-5c27b776c57f.png)

it does not save the new prop, but the thing editor is not visible anymore at the bottom.

If I hit done, no deploy is available, becasue the new prop was not saved

**Comment by Fernando-Checa** [comment]
I made a backup and deleted all thongs nodes, uninstalled things, restarted NR and reinstalled things.
No change. 
Still can't add or edit things.

**Comment by hufftheweevil** [comment]
Sorry, for the delay, but I finally found and patched this bug.
For reference, it was only affecting those still using the `ace` editor.
Note that the `ace` editor is still available in Node-RED v3, but [will be removed in v4](https://nodered.org/blog/2022/07/14/version-3-0-released#monaco-text-editor).

**Comment by Fernando-Checa** [comment]
Thanks!
I'll be sure to upgrade to the new editor soon.

Best regards

Un cordial saludo,
[m1.png]

Fernando Checa Manrique de Lara
ARQUITECTO
 Certified Passivhaus Designer  [transparent-passive-house64.gif]


+34 616 452 404
***@***.***

[m2.png]


On 25/10/2022 0:48:48, Justin ***@***.***> wrote:
Sorry, for the delay, but I finally found and patched this bug.
For reference, it was only affecting those still using the ace editor.
Note that the ace editor is still available in Node-RED v3, but will be removed in v4 [https://nodered.org/blog/2022/07/14/version-3-0-released#monaco-text-editor].
